### ISSUE TITLE
FNF Expansion Can't Detect the Extra Records Core

### ISSUE THREAD

**Issue by KirbyKid256** [RacoonDog/Extra-Records#1]
Hi, so I found what might be the problem with the FNF Expansion for Extra Records. It's that, for some reason, it can't detect the Extra Records Core mod even though I have the core in my mods folder.
[latest.log](https://github.com/RacoonDog/Extra-Records/files/7026106/latest.log)

**Comment by crosby-moe** [comment]
Oh boy yeah it was all badly made
